ALTER TYPE "InAppNotificationType" ADD VALUE IF NOT EXISTS 'ORDER_STATUS_CHANGED';
ALTER TYPE "InAppNotificationType" ADD VALUE IF NOT EXISTS 'ORDER_UPDATED';
ALTER TYPE "InAppNotificationType" ADD VALUE IF NOT EXISTS 'ORDER_DISCOUNT';
ALTER TYPE "InAppNotificationType" ADD VALUE IF NOT EXISTS 'PROJECT_UPDATED';
ALTER TYPE "InAppNotificationType" ADD VALUE IF NOT EXISTS 'SYSTEM';
