// Every API request is fulfilled locally; no working database is touched.
const { chromium } = require('C:/Users/Михаил/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const financials = {clientSubtotal: 100000, internalSubtotal: 60000, cashInternalCostTax: 0, internalExpensesTotal: 60000, commission: 0, clientChargeTax: 0, revenueTotal: 100000, tax: 0, grossMargin: 40000, marginAfterTax: 40000, marginAfterTaxPct: 40};
const projects = Array.from({length:24}, (_,i)=>({projectId:`p${i}`,title:`Демо-проект ${String(i+1).padStart(2,'0')}`,customerId:`c${i%5}`,customerName:`Демо-клиент ${i%5+1}`,status:i%6===0?'CANCELLED':i%3===0?'IN_PROGRESS':'COMPLETED',archived:false,createdAt:'2026-01-01',updatedAt:'2026-09-01',eventStartDate:'2026-09-12',eventEndDate:'2026-09-12',eventDateConfirmed:true,ordersCount:2,estimateVersionsCount:2,hasPrimaryEstimate:i!==1,hasLinkedOrder:true,daysSinceActivity:8,currentStatusAgeDays:8,healthScore:80,risks:i%4===0?['Низкая маржа']:[],financials:{...financials,revenueTotal:100000+i*1000}}));
const customers=Array.from({length:5},(_,i)=>({customerId:`c${i}`,customerName:`Демо-клиент ${i+1}`,projectsCount:5,activeProjects:1,completedProjects:3,cancelledProjects:1,forecastRevenue:400000,forecastMarginAfterTax:150000,averageProjectRevenue:100000,averageMarginAfterTaxPercent:40,closedOrdersFactRevenue:50000,ltvMixed:450000,repeat:true,completionRatePercent:60,cancelRatePercent:20}));
const timeline=[5,6,7,8,9].map((m,i)=>({month:`2026-${String(m).padStart(2,'0')}`,revenue:[320000,480000,150000,550000,600000][i],profit:[150000,420000,-50000,370000,510000][i],orders:8,projects:2}));
const fact={standaloneOrdersRevenue:1300000,standaloneOrdersProfit:1080000,completedProjectsRevenue:800000,completedProjectsProfit:320000,revenueTotal:2100000,profitTotal:1400000};
const forecast={standaloneOrdersRevenue:180000,standaloneOrdersProfit:80000,standaloneOrdersTotal:2,activeProjectsRevenue:300000,activeProjectsProfit:100000,revenueTotal:480000,profitTotal:180000};
const data={period:{from:'2026-05-01',to:'2026-09-30',dateBasis:'demo'},overview:{kpi:{ordersClosed:40,completedProjects:11,activeProjects:1},finance:{fact,forecast,bonuses:{ratePercent:15,recipients:2,factPool:210000,factPerPerson:105000,forecastPool:27000,forecastPerPerson:13500},ownership:{linkedOrdersExcluded:6,linkedClosedOrdersExcluded:6}},attention:projects.slice(0,3).map(p=>({type:'margin',severity:'warning',projectId:p.projectId,projectTitle:p.title,message:'Проверьте цену и расходы'})),topProjects:projects,topCustomers:customers,topItems:[{itemId:'i1',itemName:'Шатёр 3×3',revenue:140000}],timeline},projects:{rows:projects,risks:projects.filter(p=>p.risks.length),kpi:{},byStatus:[{status:'COMPLETED',count:16},{status:'IN_PROGRESS',count:4},{status:'CANCELLED',count:4}],statusAging:[],funnel:{}},customers:{rows:customers,kpi:{}},requisites:{kpi:{ordersTotal:50,ordersClosed:40,totalRevenue:1300000,itemsRevenue:1000000,servicesRevenue:300000,profitEstimate:1080000,averageOrderRevenue:32500,averageRentalDays:2,linkedOrdersExcluded:6,linkedClosedOrdersExcluded:6},forecast:{ordersTotal:2,totalRevenue:180000,profitEstimate:80000},breakdowns:{byStatus:[],bySource:[],revenueByMonth:timeline},tops:{topByIssued:[{itemId:'i1',itemName:'Шатёр 3×3',issuedQty:18}],topByRevenue:[{itemId:'i1',itemName:'Шатёр 3×3',revenue:140000}],topCustomers:[],customerTotals:[]},services:{deliveryRevenue:150000,montageRevenue:100000,demontageRevenue:50000,deliveryOrders:20,montageOrders:10,demontageOrders:8},profitability:{summary:{},rows:[{itemId:'i1',itemName:'Шатёр 3×3',itemType:'ASSET',totalQty:10,unitPurchasePrice:5000,purchaseCost:50000,revenue:140000,grossProfit:100000,paybackRatio:2.8,roiPercent:180,internalOnly:false,isActive:true}]}},methodology:[]};
data.facts=[];
data.projects.unassigned=[{...projects[1],projectId:'undated',title:'Демо без даты',eventStartDate:null,eventEndDate:null}];
data.requisites.facts=[];
data.requisites.items=Array.from({length:81},(_,i)=>({itemId:'i'+i,itemName:'Позиция '+i,revenue:140000/(i+1),issuedQty:i+1,linkedIssuedQty:2,purchaseCost:i===0?0:i===1?null:50000,unitPurchasePrice:i===1?null:5000,totalQty:10,paybackRatio:i===1?null:2.8,internalOnly:false,isActive:true}));
data.requisites.forecast.customerTotals=[];
data.overview.finance.bonuses.factShares=[105000,105000];
data.overview.finance.bonuses.forecastShares=[13500,13500];
for(const row of customers){row.closedOrdersCount=2;row.activeOrdersRevenue=10000;row.activeOrdersCount=1;}
async function main(){
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1586,height:992},reducedMotion:'reduce'});
 const errors=[];let reads=0;const writes=[];let fail=false;let saved=false;
 const rows=['MATCHED','CONFLICT','UNMATCHED','IGNORED'].map((matchStatus,i)=>({rowNumber:i+1,projectName:`Демо-строка ${i+1}`,revenue:100000,expenses:60000,profit:40000,marginPercent:40,bonusPool:6000,matchStatus,matchedEntityType:i===0?'PROJECT':null,matchedEntityId:i===0?'p1':null,matchNote:'Демонстрационное сопоставление'}));
 const batch={id:'b1',title:'Демо-сверка',sourceFileName:'demo.xlsx',sheetName:'Лист1',periodStart:'2026-05-02',periodEnd:'2026-09-30',createdAt:'2026-10-08',_count:{rows:4}};
 const totals={revenue:400000,expenses:240000,profit:160000,bonusPool:24000};
 const selected={...batch,rows,summary:{external:totals,site:{...totals,revenue:390000},delta:{revenue:10000,expenses:0,profit:0,bonusPool:0},matched:1,conflicts:1,unmatched:1}};
 await context.addInitScript(()=>localStorage.setItem('wowstorg.analytics.scopes.v2',JSON.stringify(Object.fromEntries(['overview','projects','customers','requisites','bonuses','reconciliation'].map(key=>[key,{from:'2026-05-01',to:'2026-09-30'}])))));
 await context.route('**/api/**',async route=>{const url=new URL(route.request().url());let result={};if(route.request().method()!=='GET')writes.push({path:url.pathname,body:route.request().postData()});if(url.pathname==='/api/auth/me')result={user:{id:'u',displayName:'Демо',role:'WOWSTORG',login:'demo'}};if(url.pathname==='/api/admin/analytics'){reads++;if(fail)return route.fulfill({status:500,json:{error:'demo'}});result=data;}if(url.pathname.endsWith('/reconciliation')){if(route.request().method()==='POST'){if(route.request().postData().includes('\r\ncommit\r\n')){saved=true;result={batchId:'b1'};}else result={preview:{fileName:'demo.xlsx',sheetName:'Лист1',rows,totals,matched:1,conflicts:1,unmatched:1}};}else result={batches:saved?[batch]:[],selected:url.searchParams.get('id')==='b1'?selected:null};}await route.fulfill({status:200,json:result});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3102/admin/analytics');await page.addStyleTag({content:'nextjs-portal{display:none!important}'});await page.getByRole('heading',{name:'Выручка и прибыль по месяцам'}).waitFor();await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(400);
 await page.screenshot({path:path.join(__dirname,'hero-repro.png')});
 if(process.argv.includes('--hero')){await browser.close();console.log('HERO_CAPTURED');return;}
 const overflow=async()=>{const result=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,over:[...document.querySelectorAll('section,div,table,svg,h1,input')].map(e=>({tag:e.tagName,c:e.className?.baseVal??e.className,x:e.getBoundingClientRect().x,w:e.getBoundingClientRect().width})).filter(r=>r.x+r.w>innerWidth+1&&r.x>=0).slice(0,20)}));if(result.scroll>result.width)console.log(JSON.stringify(result));if(result.scroll>result.width)console.log(await page.locator('table').evaluate(e=>{const a=[];for(let n=e;n;n=n.parentElement){const r=n.getBoundingClientRect(),c=getComputedStyle(n);a.push({tag:n.tagName,cls:n.className,w:r.width,x:r.x,overflow:c.overflowX,min:c.minWidth,display:c.display})}return a}));assert.equal(result.scroll>result.width,false);};
 for(const tab of ['Обзор','Проекты','Клиенты','Реквизит','Бонусы','Сверка']){await page.getByRole('navigation',{name:'Разделы аналитики'}).getByRole('button',{name:tab,exact:true}).click();await page.waitForTimeout(150);await overflow();await page.screenshot({path:path.join(__dirname,`analytics-${tab}.png`),fullPage:true});}
 await page.getByRole('navigation',{name:'Разделы аналитики'}).getByRole('button',{name:'Проекты',exact:true}).click();await page.getByRole('searchbox').fill('проект 02');assert.equal(await page.locator('table').last().locator('tbody tr').count(),1);await page.getByRole('searchbox').fill('');await page.getByRole('button',{name:'Далее',exact:true}).click();assert((await page.locator('main').innerText()).includes('11–20'));await page.getByRole('button',{name:/Показать подробности/}).first().click();assert(await page.locator('[aria-expanded=true]').count()>0);
 assert.equal(reads,1,'same period reuses the full read model across tabs');
 await page.getByRole('navigation',{name:'Разделы аналитики'}).getByRole('button',{name:'Обзор',exact:true}).click();fail=true;await page.getByRole('button',{name:'Обновить',exact:true}).click();await page.getByRole('button',{name:'Повторить',exact:true}).waitFor();fail=false;await page.getByRole('button',{name:'Повторить',exact:true}).click();await page.getByRole('heading',{name:'Выручка и прибыль по месяцам'}).waitFor();
 for(const width of [1440,390]){await page.setViewportSize({width,height:width===390?844:1000});for(const tab of ['Обзор','Проекты','Клиенты','Реквизит','Бонусы','Сверка']){await page.getByRole('navigation',{name:'Разделы аналитики'}).getByRole('button',{name:tab,exact:true}).click();await overflow();await page.screenshot({path:path.join(__dirname,`analytics-${tab}-${width}.png`),fullPage:true});}}
 assert.deepEqual(writes,[]);
 await page.setViewportSize({width:1440,height:1000});
 const nav=page.getByRole('navigation',{name:'Разделы аналитики'});
 await nav.getByRole('button',{name:'Проекты',exact:true}).click();await page.locator('details[class*="datePicker"]').first().locator('summary').click();await page.getByLabel('Начало периода').fill('2026-05-02');await page.locator('details[class*="datePicker"]').first().locator('summary').click();
 await nav.getByRole('button',{name:'Обзор',exact:true}).click();assert((await page.locator('details[class*="datePicker"]').first().innerText()).includes('02.05.2026'));
 await nav.getByRole('button',{name:'Проекты',exact:true}).click();assert((await page.locator('details[class*="datePicker"]').first().innerText()).includes('02.05.2026'));
 await nav.getByRole('button',{name:'Сверка',exact:true}).click();await page.getByLabel('Файл Excel').setInputFiles({name:'demo.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from('synthetic intercepted request')});await page.getByRole('button',{name:'Проверить файл',exact:true}).click();await page.getByRole('heading',{name:'Предварительное сопоставление'}).waitFor();assert.equal(await page.locator('table').last().locator('tbody tr').count(),4);
 await page.locator('details[class*="datePicker"]').first().locator('summary').click();await page.getByLabel('Начало периода').fill('2026-05-02');await page.locator('details[class*="datePicker"]').first().locator('summary').click();assert(await page.getByRole('button',{name:'Сохранить снимок',exact:true}).isDisabled());await page.getByRole('button',{name:'Проверить файл',exact:true}).click();await page.getByRole('button',{name:'Сохранить снимок',exact:true}).click();await page.getByRole('heading',{name:'Разница с сайтом'}).waitFor();
 await page.getByRole('button',{name:'Конфликт',exact:true}).click();assert.equal(await page.locator('table').last().locator('tbody tr').count(),1);await page.getByRole('button',{name:'Все',exact:true}).click();await page.getByRole('button',{name:/Показать подробности/}).first().click();
 for(const width of [1440,390]){await page.setViewportSize({width,height:width===390?844:1000});await nav.getByRole('button',{name:'Сверка',exact:true}).scrollIntoViewIfNeeded();await page.evaluate(()=>window.scrollTo(0,0));await overflow();await page.screenshot({path:path.join(__dirname,`analytics-reconciliation-result-${width}.png`),fullPage:true});}
 assert.equal(writes.length,3);assert(writes.every(w=>w.path==='/api/admin/analytics/reconciliation'));assert(writes[2].body.includes('2026-05-02'));assert.deepEqual(errors,[]);await browser.close();console.log(JSON.stringify({status:'PASS',reads,synthetic:true,assertions:['all six tabs','shared cache','search','pagination','details','retry','desktop/mobile overflow','shared core periods and independent reconciliation','preview context guard','snapshot save/filter/details','only mocked writes','no browser errors']}));
}
main().catch(e=>{console.error(e);process.exit(1)});
