"use client";

import Link from "next/link";
import React from "react";
import type { AdminAnalyticsData, ProjectAnalyticsRow } from "@/server/admin-analytics";
import { analyticsCustomerRows, analyticsMargin, completeAnalyticsTimeline, isActiveAnalyticsProject } from "@/lib/analytics-presentation";
import { Column, date, Filters, Methodology, Metrics, money, Panel, percent, SmartTable, status, Trend } from "./AnalyticsUI";
import { projectActualDate, sumAnalyticsMoney } from "@/lib/analytics-finance";
import s from "./analytics.module.css";
import { ProjectDatesEditor } from "./ProjectDatesEditor";
type Scope = { from: string; to: string };
const sum = <T,>(rows: T[], value: (row: T) => number) => sumAnalyticsMoney(rows.map(value));
const ratio = (value: number | null) => value == null ? "—" : `${value.toLocaleString("ru-RU", { maximumFractionDigits: 2 })}×`;
function Detail({ label, children }: { label: string; children: React.ReactNode }) { return <div><span className={s.label}>{label}</span><strong>{children}</strong></div>; }
function ProjectMoney({ row }: { row: ProjectAnalyticsRow }) { return <>{(row.hasFinancialData ?? row.hasPrimaryEstimate) && row.status !== "CANCELLED" ? <><Detail label="Внутренние расходы">{money(row.financials.internalExpensesTotal)}</Detail><Detail label="Налог">{money(row.financials.tax)}</Detail><Detail label="Комиссия">{money(row.financials.commission)}</Detail></> : <Detail label="Финансы">{row.status === "CANCELLED" ? "Отменён — не входит в результат" : "Нет учитываемой сметы"}</Detail>}<Detail label="Учитываемые сметы / связанные заявки">{row.includedEstimatesCount ?? row.estimateVersionsCount} / {row.ordersCount}</Detail>{!row.hasPrimaryEstimate && row.hasFinancialData && <Detail label="Источник бюджета">Черновой реквизит; учитываемой сметы пока нет</Detail>}<Detail label="Без активности">{row.daysSinceActivity} дн.</Detail><Detail label="Риски">{row.risks.length ? row.risks.join(" · ") : "Нет"}</Detail></>; }

export function AnalyticsProjects({ data, onDatesChanged }: { data: AdminAnalyticsData; onDatesChanged: () => void }) {
  const [filter, setFilter] = React.useState("all");
  const all = data.projects.rows;
  const active = all.filter(isActiveAnalyticsProject);
  const completed = all.filter(row => row.status === "COMPLETED");
  const riskIds = new Set(data.projects.risks.map(row => row.projectId));
  const rows = all.filter(row => filter === "all" || filter === "active" && isActiveAnalyticsProject(row) || filter === "complete" && row.status === "COMPLETED" || filter === "cancelled" && row.status === "CANCELLED" || filter === "risks" && riskIds.has(row.projectId));
  const columns: Column<ProjectAnalyticsRow>[] = [
    { key: "title", label: "Проект / клиент", minWidth: 180, sort: row => row.title, render: row => <><Link href={`/projects/${row.projectId}`} className={s.cellTitle}>{row.title}</Link><p className={s.note}>{row.customerName}</p></> },
    { key: "status", label: "Состояние", sort: row => status(row.status), render: row => <><span className={s.badge}>{status(row.status)}</span>{row.archived && <p className={s.note}>Архив</p>}</> },
    { key: "date", label: "Дата", sort: row => projectActualDate(row), render: row => <>{!row.eventStartDate && !row.eventEndDate ? <>{date(projectActualDate(row))}<p className={s.note}>По дате закрытия</p></> : <>{date(row.eventStartDate ?? row.eventEndDate)}{row.eventStartDate && row.eventEndDate && row.eventEndDate !== row.eventStartDate && <> — {date(row.eventEndDate)}</>}{!row.eventDateConfirmed && <p className={s.note}>Дата не подтверждена</p>}</>}<ProjectDatesEditor row={row} onSaved={onDatesChanged} /></> },
    { key: "revenue", label: "Выручка", numeric: true, sort: row => (row.hasFinancialData ?? row.hasPrimaryEstimate) && row.status !== "CANCELLED" ? row.financials.revenueTotal : null, render: row => (row.hasFinancialData ?? row.hasPrimaryEstimate) && row.status !== "CANCELLED" ? money(row.financials.revenueTotal) : "—" },
    { key: "profit", label: "Прибыль", numeric: true, sort: row => (row.hasFinancialData ?? row.hasPrimaryEstimate) && row.status !== "CANCELLED" ? row.financials.marginAfterTax : null, render: row => (row.hasFinancialData ?? row.hasPrimaryEstimate) && row.status !== "CANCELLED" ? <span className={row.financials.marginAfterTax < 0 ? s.negative : s.positive}>{money(row.financials.marginAfterTax)}</span> : "—" },
    { key: "margin", label: "Маржа", numeric: true, sort: row => (row.hasFinancialData ?? row.hasPrimaryEstimate) && row.status !== "CANCELLED" ? analyticsMargin(row.financials.revenueTotal, row.financials.marginAfterTax) : null, render: row => (row.hasFinancialData ?? row.hasPrimaryEstimate) && row.status !== "CANCELLED" ? percent(analyticsMargin(row.financials.revenueTotal, row.financials.marginAfterTax)) : "—" },
  ];
  return <div className={s.stack}><Metrics items={[{ label: "Выручка завершённых", value: money(sum(completed, row => row.financials.revenueTotal)), note: `${completed.length} проектов` }, { label: "Прогноз активных", value: money(sum(active, row => row.financials.revenueTotal)), note: `${active.length} проектов` }, { label: "Прибыль активных", value: money(sum(active, row => row.financials.marginAfterTax)) }, { label: "Требуют внимания", value: riskIds.size, note: "Уникальные проекты" }]} /><Panel title="Проекты за период"><SmartTable rows={rows} columns={columns} rowKey={row => row.projectId} searchText={row => `${row.title} ${row.customerName}`} searchLabel="Найти проект или клиента" defaultSort="revenue" details={row => <ProjectMoney row={row} />} toolbar={<Filters value={filter} onChange={setFilter} items={[{ value: "all", label: "Все" }, { value: "active", label: "В работе" }, { value: "complete", label: "Завершены" }, { value: "risks", label: "С рисками" }, { value: "cancelled", label: "Отменены" }]} />} /><Methodology>Факт — завершённые проекты по окончанию мероприятия (если окончания нет — по началу). Если обе даты отсутствуют — по дате закрытия в Омске. Прогноз — активные проекты, пересекающие период. В сумму входят все сметы с включённым учётом в проекте; отменённые не учитываются.</Methodology></Panel></div>;
}

export function AnalyticsCustomers({ data }: { data: AdminAnalyticsData }) {
  const [filter, setFilter] = React.useState("all");
  const all = React.useMemo(() => analyticsCustomerRows(data), [data]);
  const rows = all.filter(row => filter === "all" || filter === "actual" && row.completedProjects + (row.closedOrdersCount ?? 0) > 0 || filter === "active" && (row.projects.some(isActiveAnalyticsProject) || row.activeOrdersCount > 0));
  type Row = typeof all[number];
  const columns: Column<Row>[] = [
    { key: "name", label: "Клиент", minWidth: 180, sort: row => row.customerName, render: row => <strong className={s.cellTitle}>{row.customerName}</strong> },
    { key: "actual", label: "Выручка · факт", numeric: true, sort: row => row.actualRevenue, render: row => money(row.actualRevenue) },
    { key: "projectFact", label: "Из проектов", numeric: true, sort: row => row.actualProjects, render: row => money(row.actualProjects) },
    { key: "orderFact", label: "Из заявок", numeric: true, sort: row => row.closedOrdersFactRevenue, render: row => money(row.closedOrdersFactRevenue) },
    { key: "active", label: "В работе · прогноз", numeric: true, sort: row => row.activeRevenue, render: row => money(row.activeRevenue) },
  ];
  const actualClients = all.filter(row => row.completedProjects + (row.closedOrdersCount ?? 0) > 0);
  const activeClients = all.filter(row => row.projects.some(isActiveAnalyticsProject) || row.activeOrdersCount > 0);
  return <div className={s.stack}><Metrics items={[{ label: "Клиенты с завершёнными работами", value: actualClients.length }, { label: "Выручка завершённых работ", value: money(sum(all, row => row.actualRevenue)) }, { label: "Клиенты с активными работами", value: activeClients.length }, { label: "Активные работы · прогноз", value: money(sum(all, row => row.activeRevenue)) }]} /><Panel title="Клиентская база за период"><SmartTable rows={rows} columns={columns} rowKey={row => row.customerId} searchText={row => row.customerName} searchLabel="Найти клиента" defaultSort="actual" toolbar={<Filters value={filter} onChange={setFilter} items={[{ value: "all", label: "Все" }, { value: "actual", label: "Есть завершённые работы" }, { value: "active", label: "Есть активные работы" }]} />} details={row => <><Detail label="Завершённые проекты">{money(row.actualProjects)}</Detail><Detail label="Самостоятельные закрытые заявки">{money(row.closedOrdersFactRevenue)}</Detail><Detail label="Средний бюджет проекта">{row.averageEstimatedProject == null ? "—" : money(row.averageEstimatedProject)}</Detail><Detail label="Завершённых работ">{row.completedProjects} проектов · {row.closedOrdersCount ?? 0} заявок</Detail><Detail label="Прогноз проектов / заявок">{money(row.activeProjectsRevenue)} / {money(row.activeOrdersRevenue ?? 0)}</Detail><Detail label="Маржа только проектов">{percent(row.projectMargin)}</Detail>{row.incompleteCompleted > 0 && <Detail label="Не хватает данных">{row.incompleteCompleted} завершённых проектов без учитываемой сметы</Detail>}<div><span className={s.label}>Самостоятельные закрытые заявки</span>{data.facts.filter(fact => fact.source === "ORDER" && fact.customerId === row.customerId).map(fact => <div key={fact.id}><Link href={`/orders/${fact.id}`} className={s.cellTitle}>Заявка · {date(fact.date)}</Link><span className={s.note}> · {money(fact.revenue)}</span></div>)}</div><div><span className={s.label}>Проекты клиента</span>{row.projects.length ? row.projects.map(project => <div key={project.projectId}><Link href={`/projects/${project.projectId}`} className={s.cellTitle}>{project.title}</Link><span className={s.note}> · {status(project.status)}</span></div>) : "Нет проектов за период"}</div></>} /><Methodology>Факт = завершённые проекты + закрытые самостоятельные заявки за общий с обзором период. Заявки внутри проектов не прибавляются повторно. Прогноз включает активные проекты и самостоятельные заявки. Это выручка за период, не пожизненный LTV и не оплаченные счета.</Methodology></Panel></div>;
}

export function AnalyticsRequisites({ data, scope }: { data: AdminAnalyticsData; scope: Scope }) {
  const [filter, setFilter] = React.useState("all");
  const r = data.requisites;
  const rows = r.items.filter(row => filter === "all" || filter === "earned" && row.revenue !== 0 || filter === "issued" && row.issuedQty + row.linkedIssuedQty > 0 || filter === "noCost" && row.purchaseCost == null);
  type Row = typeof rows[number];
  const columns: Column<Row>[] = [
    { key: "name", label: "Позиция", minWidth: 180, sort: row => row.itemName, render: row => <strong className={s.cellTitle}>{row.itemName}</strong> },
    { key: "issued", label: "Выдано, шт.", numeric: true, sort: row => row.issuedQty + row.linkedIssuedQty, render: row => row.issuedQty + row.linkedIssuedQty },
    { key: "revenue", label: "Самостоятельный прокат", numeric: true, sort: row => row.revenue, render: row => money(row.revenue) },
    { key: "cost", label: "Стоимость парка", numeric: true, sort: row => row.purchaseCost, render: row => row.purchaseCost == null ? "Не задана" : money(row.purchaseCost) },
    { key: "payback", label: "Выручка / парк", numeric: true, sort: row => row.paybackRatio, render: row => ratio(row.paybackRatio) },
  ];
  const points = completeAnalyticsTimeline(r.breakdowns.revenueByMonth.map(point => ({ ...point, projects: 0 })), scope.from, scope.to);
  return <div className={s.stack}><Metrics items={[{ label: "Выручка проката и услуг", value: money(r.kpi.totalRevenue), note: `${r.kpi.ordersClosed} закрытых заявок` }, { label: "Расчётная прибыль", value: money(r.kpi.profitEstimate), positive: r.kpi.profitEstimate >= 0 }, { label: "Средний чек заявки", value: money(r.kpi.averageOrderRevenue) }, { label: "Выручка в работе", value: money(r.forecast.totalRevenue), note: `${r.forecast.ordersTotal} заявок` }]} /><div className={s.chartRow}><Panel title="Прокат по месяцам"><Trend points={points} /></Panel><Panel title="Услуги в закрытых заявках">{[{ label: "Доставка", value: r.services.deliveryRevenue, count: r.services.deliveryOrders }, { label: "Монтаж", value: r.services.montageRevenue, count: r.services.montageOrders }, { label: "Демонтаж", value: r.services.demontageRevenue, count: r.services.demontageOrders }].map(row => <div key={row.label} className={s.signal}><span><strong>{row.label}</strong><small>{row.count} заявок</small></span><strong>{money(row.value)}</strong></div>)}</Panel></div><Panel title="Спрос и выручка позиций"><SmartTable rows={rows} columns={columns} rowKey={row => row.itemId} searchText={row => row.itemName} searchLabel="Найти позицию" defaultSort="revenue" toolbar={<Filters value={filter} onChange={setFilter} items={[{ value: "all", label: "Все" }, { value: "earned", label: "С выручкой" }, { value: "issued", label: "Есть выдачи" }, { value: "noCost", label: "Без закупочной цены" }]} />} details={row => <><Detail label="Выдано в самостоятельных заявках">{row.issuedQty}</Detail><Detail label="Выдано в проектах">{row.linkedIssuedQty}</Detail><Detail label="Количество в парке">{row.totalQty}</Detail><Detail label="Закупка за единицу">{row.unitPurchasePrice == null ? "Не задана" : money(row.unitPurchasePrice)}</Detail><Detail label="Доступность">{row.isActive ? "Активна" : "Скрыта"}{row.internalOnly ? " · внутреннее использование" : ""}</Detail></>} /><details className={s.help}><summary>О показателях реквизита</summary><p>Список содержит все позиции, не только лидеров. Выдачи включают закрытые самостоятельные заявки и заявки проектов с окончанием в периоде. Выручка — только самостоятельная аренда, после скидок, без услуг и клиентского налога. Стоимость парка — текущая закупочная оценка, не расходы периода. Выручка / парк — отношение за выбранный период, не прибыль и не пожизненная окупаемость.</p></details></Panel></div>;
}

export function AnalyticsBonuses({ data }: { data: AdminAnalyticsData }) {
  const { fact, forecast, bonuses: bonus } = data.overview.finance;
  return <div className={s.stack}><Metrics items={[{ label: "Бонусный пул · факт", value: money(bonus.factPool), note: `${bonus.ratePercent}% от прибыли` }, { label: "На человека", value: money(bonus.factPerPerson), note: `${bonus.recipients} получателей${bonus.factShares?.[1] !== bonus.factPerPerson ? ` · второму ${money(bonus.factShares[1])}` : ""}` }, { label: "Прибыль для расчёта", value: money(fact.profitTotal), positive: fact.profitTotal >= 0 }]} /><div className={s.lowerRow}><Panel title="Расчёт за период">{[{ label: "Прибыль самостоятельных заявок", value: fact.standaloneOrdersProfit }, { label: "Прибыль завершённых проектов", value: fact.completedProjectsProfit }, { label: `Бонусный пул · ${bonus.ratePercent}%`, value: bonus.factPool }, { label: `На человека · ÷ ${bonus.recipients}`, value: bonus.factPerPerson }].map(row => <div className={s.formula} key={row.label}><span>{row.label}</span><strong>{money(row.value)}</strong></div>)}<p className={s.note}>Расчётный пул, не подтверждение выплаты. Доли: {bonus.factShares.map(money).join(" + ")}.</p><Methodology>Связанные заявки не дублируют прибыль проектов. Пул — процент от суммарной прибыли самостоятельных закрытых заявок и завершённых проектов; сумма на человека — пул, разделённый на число получателей.</Methodology></Panel><Panel title="Потенциальный бонус"><div className={s.formula}><span>Пул по активным работам</span><strong>{money(bonus.forecastPool)}</strong></div><div className={s.formula}><span>На человека</span><strong>{money(bonus.forecastPerPerson)}</strong></div><div className={s.formula}><span>Прогноз прибыли</span><strong>{money(forecast.profitTotal)}</strong></div><p className={s.note}>Не начислено. Итог изменится после завершения работ и уточнения расходов.</p></Panel></div></div>;
}
/** Undated work remains discoverable across periods; closure is provisional, never an event date. */
export function AnalyticsDataQuality({ data, onDatesChanged }: { data: AdminAnalyticsData; onDatesChanged: () => void }) {
  const rows = [...data.projects.unassigned, ...(data.projects.pendingDates ?? [])];
  if (!rows.length) return null;
  return <details className={s.dataQuality}><summary>Уточните даты мероприятия: {rows.length}</summary>
    <p className={s.note}>Список показан независимо от периода. Завершённые проекты временно учитываются по дате закрытия. Укажите даты мероприятия здесь — выручка перейдёт в нужный период. Активные проекты без дат не входят в прогноз.</p>
    <SmartTable rows={rows} columns={[
      { key: "name", label: "Проект / клиент", render: row => <><Link href={`/projects/${row.projectId}`} className={s.cellTitle}>{row.title}</Link><p className={s.note}>{row.customerName}</p></> },
      { key: "status", label: "Статус", render: row => status(row.status) },
      { key: "date", label: "Дата учёта", render: row => <>{date(projectActualDate(row))}{row.closedDate && <p className={s.note}>По закрытию · требует уточнения</p>}<ProjectDatesEditor row={row} onSaved={onDatesChanged} /></> },
      { key: "money", label: "Бюджет смет", numeric: true, sort: row => row.financials.revenueTotal, render: row => money(row.financials.revenueTotal) },
    ]} rowKey={row => row.projectId} searchText={row => `${row.title} ${row.customerName}`} searchLabel="Найти проект без даты" defaultSort="money" />
  </details>;
}
